module.exports={
    "presets": [{
        "name": "dinner",
        "preset": [{
            "device": "LUSTRE_ENTRE",
            "level": "70"
        }, {
            "device": "LUSTRE_TABLE",
            "level": "70"
        }, {
            "device": "LUSTRE_SALON",
            "level": "80"
        }, {
            "device": "LAMPE_RENARD",
            "level": "on"
        }, {
            "device": "LAMPE_MUR_PANTERE",
            "level": "on"
        }, {
            "device": "LAMPE_TELE",
            "level": "on"
        }, {
            "device": "LAMPE_PANDULE",
            "level": "on"
        }]
    }, {
        "name": "TV",
        "preset": [{
            "device": "LUSTRE_ENTRE",
            "level": "30"
        }, {
            "device": "LUSTRE_TABLE",
            "level": "30"
        }, {
            "device": "LUSTRE_SALON",
            "level": "30"
        }, {
            "device": "LAMPE_RENARD",
            "level": "off"
        }, {
            "device": "LAMPE_MUR_PANTERE",
            "level": "off"
        }, {
            "device": "LAMPE_TELE",
            "level": "on"
        }, {
            "device": "LAMPE_PANDULE",
            "level": "on"
        }]
    },{
        "name": "off",
        "preset": [{
            "device": "LUSTRE_ENTRE",
            "level": "0"
        }, {
            "device": "LUSTRE_TABLE",
            "level": "0"
        }, {
            "device": "LUSTRE_SALON",
            "level": "0"
        }, {
            "device": "LAMPE_RENARD",
            "level": "off"
        }, {
            "device": "LAMPE_MUR_PANTERE",
            "level": "off"
        }, {
            "device": "LAMPE_TELE",
            "level": "off"
        }, {
            "device": "LAMPE_PANDULE",
            "level": "off"
        }]
    },{
        "name": "all-on",
        "preset": [{
            "device": "LUSTRE_ENTRE",
            "level": "100"
        }, {
            "device": "LUSTRE_TABLE",
            "level": "100"
        }, {
            "device": "LUSTRE_SALON",
            "level": "100"
        }, {
            "device": "LAMPE_RENARD",
            "level": "on"
        }, {
            "device": "LAMPE_MUR_PANTERE",
            "level": "on"
        }, {
            "device": "LAMPE_TELE",
            "level": "on"
        }, {
            "device": "LAMPE_PANDULE",
            "level": "on"
        }]
    }]
}
